name: navdump-gen

on:
  push:
    paths:
      - 'root/maps/**.nav'
  workflow_dispatch:
  
jobs:
  build:
    name: Generate NAV dump
    runs-on: ubuntu-latest
    steps:
      - name: Getting own repository
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Setting up Python
        uses: actions/setup-python@v2
          
      - name: Generate NAV dump files
        shell: bash
        working-directory: repo
        run: |
          python ../.github/navdump.py
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'repo/.gen/nav/*.nav.txt'
          default_author: 'github_actions'
