name: navdump-gen

on:
  push:
    paths:
      - 'root/maps/**.nav'
      - '.github/workflows/main.yml'
  workflow_dispatch:
  
jobs:
  build:
    name: Generate NAV dump
    runs-on: ubuntu-latest
    steps:
      - name: Getting own repository
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Setting up Python
        uses: actions/setup-python@v2
          
      - name: Install/Update dependencies
        shell: bash
        run: |
          python -m pip install binary_reader --upgrade pip
          
      - name: Generate NAV dump files
        shell: bash
        working-directory: repo
        run: |
          python .github/navdump.py -o .gen/nav root/maps/*.nav
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: '.gen/nav/*.nav.txt'
          cwd: 'repo'
          default_author: 'github_actions'
